// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylzpjjeopaodydzlunxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsenBqamVvcGFvZHlkemx1bnhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NTc4ODgsImV4cCI6MjA2ODQzMzg4OH0.sYD_xvW9idA2OfrB3KY01JjfeE-1q8i27WADcVp1qQk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});